steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA', # Changed region
        '-t',
        'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest', # Changed region
        '.',
        '-f',
        'Dockerfile',
      ]

  # Step 2a: Explicitly push the image tagged with COMMIT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-commit-sha'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA' # Changed region
      ]

  # Step 2b: Explicitly push the image tagged with 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest' # Changed region
      ]
    # Ensure this step runs after the commit sha push (usually implicit, but waitFor can be used if needed)
    # waitFor: ['push-commit-sha']

  # Step 3: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'dns-analyser',
        '--image',
        'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA', # Changed region
        '--region',
        'europe-west1', # Changed region
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--quiet',
      ]

# Specify the images to push after the build
images:
  - 'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA' # Changed region
  - 'europe-west1-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest' # Changed region

# Set build options, including logging
options:
  logging: CLOUD_LOGGING_ONLY
