steps:
  # Step 1: Build the container image (No changes here)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA',
        '-t',
        'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest',
        '.', # Build context is the current directory
        '-f',
        'Dockerfile', # Specify the Dockerfile
      ]

  # Step 2a: Explicitly push the image tagged with COMMIT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-commit-sha' # Optional ID for clarity
    args:
      [
        'push',
        'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA'
      ]

  # Step 2b: Explicitly push the image tagged with 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest' # Optional ID for clarity
    args:
      [
        'push',
        'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest'
      ]
    # Ensure this step runs after the commit sha push (usually implicit, but waitFor can be used if needed)
    # waitFor: ['push-commit-sha']

  # Step 3: Deploy container image to Cloud Run (No changes here)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'dns-analyser', # Name of your Cloud Run service
        '--image',
        'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA',
        '--region',
        'europe-west6', # Set Cloud Run region to Zurich
        '--platform',
        'managed',
        '--allow-unauthenticated', # Add this if you want public access, remove if not
        '--quiet', # Suppress interactive prompts
      ]

# Specify the images to push after the build (This section might be redundant now but doesn't hurt)
images:
  - 'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:$COMMIT_SHA'
  - 'europe-west6-docker.pkg.dev/marine-set-455317-i1/dns-analyser-repo/dns-analyser:latest'

# Set build options, including logging (No changes here)
options:
  logging: CLOUD_LOGGING_ONLY
